### PR TITLE
Update JavaScriptDescription.java

### PR DESCRIPTION
**Pull request by Ninjacoderhsi**
Add new key

### CODE REVIEW

**Comment by JavkhlanK** [comment]
I couldn't find any trustworthy webpage that defines `of` as keyword 🤔
Example: https://www.w3schools.com/js/js_reserved.asp

**Comment by PranavPurwar** [comment]
ha, jbk nub

**Comment by gianxddddd** [comment]
lmao

**Comment by PranavPurwar** [comment]
:trollface:

**Pull request merged**
